
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[238] =
    {   0,
       71,   71,   73,   73,    0,    0,   91,   89,   71,   70,
       76,   89,   46,   47,   40,   37,   50,   38,   49,   41,
       58,   58,   52,   48,   34,   51,   32,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   53,   54,   89,   72,   73,
       74,   75,   88,   87,   77,   88,   71,    0,    0,   56,
       67,   67,    0,    0,    0,   58,   55,   35,   36,   33,
       57,   57,   57,    0,   57,   57,   57,   57,   57,   57,
       23,   57,   57,   57,   57,   57,   17,   57,   57,   57,
       57,    5,   39,   57,   57,   57,   57,   57,   26,   57,

       57,   57,   57,   57,   57,   73,   86,   84,   82,   79,
       78,   81,   80,   83,   85,   60,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   68,   68,    0,    0,   59,
       43,   57,   57,   57,   57,   57,   57,   42,   57,   57,
       16,   57,   24,   57,   57,   57,   44,   45,   57,   57,
       57,   57,   57,   57,   57,    6,   57,   57,   65,   62,
       61,   64,   63,   66,    0,   67,   67,   68,   69,   69,
       59,   57,   57,   57,   20,   13,   57,   57,   19,   57,
       57,   57,   57,   57,   57,   57,   57,   27,   11,   57,
       18,   30,    3,   57,   57,   67,    0,   69,    4,   15,

       57,    2,   57,   31,   57,   57,   57,   57,   57,   57,
       57,   57,   22,   28,   57,   25,   57,   57,   57,   29,
       57,   57,   57,   14,   12,    7,   57,   10,   57,   57,
        1,    8,   57,   57,   21,    9,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    5,    5,    5,    5,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    5,    5,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   32,   33,   34,   35,   36,   37,
       32,   38,   39,   40,   41,   42,   43,   44,   45,   32,
       46,   47,   48,    5,   49,    5,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   32,   32,   59,   60,   61,
       62,   63,   32,   64,   65,   66,   67,   68,   69,   70,
       71,   32,   72,    5,   73,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[74] =
    {   0,
        1,    1,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    4,    3,    5,    6,    3,    3,    3,
        3,    3,    7,    7,    7,    7,    7,    7,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    3,    3,    3,    9,    7,
        7,    7,    7,    7,    7,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    3,   10
    } ;

static const flex_int16_t yy_base[249] =
    {   0,
        0,    0,   71,   72,   73,   74,  638,  639,   79,  639,
      639,  590,  639,  639,  639,  639,  639,  639,   68,  639,
       64,   72,  615,  639,   71,  639,  614,   52,   68,   75,
       78,   98,  105,  585,  107,  111,   61,  112,  135,  115,
      122,   63,  147,  120,  148,  639,  639,    0,  639,    0,
      639,  639,  639,  639,  639,  213,   92,  626,  275,  639,
      171,  186,   90,  178,   86,  200,  639,  639,  639,  639,
      583,  180,  144,  582,  151,  174,  181,  208,  186,  201,
      183,  200,  189,  212,  221,  227,  581,  223,  231,  241,
      235,  580,  579,  109,  242,  270,  248,  246,  578,  257,

      259,  267,  276,  280,  577,    0,  639,  639,  639,  639,
      639,  639,  639,  639,  639,  639,  618,  617,  616,  615,
      614,  613,  134,  329,  311,  639,  316,  573,  537,  536,
      500,  298,  304,  311,  260,  312,  310,  499,  302,  325,
      497,  315,  322,  332,  328,  329,  495,  493,  339,  343,
      357,  338,  351,  340,  370,  492,  368,  362,  639,  639,
      639,  639,  639,  639,  387,  639,  391,  397,  524,    0,
      522,  360,  380,  371,  486,  484,  381,  383,  479,  391,
      403,  393,  405,  397,  401,  408,  406,  478,  439,  387,
      427,  419,  394,  424,  431,  450,  422,    0,  324,  307,

      433,  274,  428,  269,  422,  438,  445,  444,  446,  449,
      456,  455,  253,  234,  465,  207,  471,  467,  443,  195,
      460,  472,  474,  185,  179,  175,  482,  173,  473,  481,
      132,  103,  483,  498,   70,   66,  639,  552,  562,  570,
      576,  579,  587,  596,  603,  606,  610,  612
    } ;

static const flex_int16_t yy_def[249] =
    {   0,
      237,    1,  238,  238,  239,  239,  237,  237,  237,  237,
      237,  240,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  237,  237,  242,  237,  243,
      237,  237,  237,  237,  237,  244,  237,  237,  237,  237,
      237,  237,  237,  237,  245,  237,  237,  237,  237,  237,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,

      241,  241,  241,  241,  241,  243,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  246,  237,  247,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  246,  248,
      247,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  237,  246,  248,  241,  241,

      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,    0,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237
    } ;

static const flex_int16_t yy_nxt[713] =
    {   0,
        8,    9,   10,    9,    8,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   34,
       35,   34,   36,   37,   38,   39,   40,   41,   42,   43,
       34,   44,   45,   34,   34,   46,    8,   47,   48,   28,
       29,   30,   31,   32,   33,   34,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   34,   44,   45,   34,
       34,   49,    8,   51,   51,   54,   54,   63,   55,   55,
       57,   60,   57,   61,   62,   63,   72,   66,   66,   73,
       64,   68,   69,   57,   75,   57,   90,   77,   64,  128,

       74,  129,   97,   76,   78,   61,   62,   65,   80,   74,
       79,   74,   72,   81,   74,   73,   74,   64,   74,   56,
       56,   75,   90,   74,   77,   64,   74,   84,   97,   76,
       82,   78,   83,   65,   87,   80,   79,   89,  149,   81,
       85,   88,  102,   52,   52,   86,   74,   91,   96,  123,
       62,   74,   95,   74,   84,   74,   82,   74,   83,   74,
       74,   87,   92,   74,   89,  149,   85,   88,   74,  102,
       74,   86,   93,   91,   94,   96,   98,  103,   95,  133,
       74,  132,   99,   74,  100,  104,  123,   62,  125,   92,
      125,  101,   74,  126,  127,   74,   74,  124,   93,   74,

       94,  123,   62,   98,  103,  131,  133,  132,   99,  134,
      100,  104,  124,   63,  141,   66,   66,  101,  108,  135,
      137,   74,   74,   74,  124,  139,   64,   74,   74,   74,
      136,   74,  131,   74,   74,  134,  109,   74,  140,  124,
      110,  141,  138,   74,  142,  135,  137,  111,   74,   74,
      112,  139,  113,   64,  114,   74,   74,  136,  143,  115,
       74,  144,  145,  109,  140,  146,  147,  110,  138,   74,
      142,   74,  153,  111,  148,   74,  112,  150,  113,   74,
      114,  116,   74,   74,  143,  152,  175,  144,  145,   74,
       74,  146,  151,  147,   74,  155,   74,  154,  117,  153,

      148,   74,  118,  150,  156,   74,  157,   74,   74,  119,
      158,  152,  120,  175,  121,   74,  122,   74,   74,  151,
      172,  155,   74,  154,   74,  117,  126,  127,   74,  118,
      156,  168,  168,  157,  173,  119,  178,  158,  120,  165,
      121,  165,  122,  174,  166,  167,   74,  172,  177,  176,
       74,  179,   74,  180,  183,   74,  182,  184,   74,   74,
       74,  173,  178,   74,  181,  185,  192,  186,  190,  174,
       74,  187,   74,   74,  177,  176,   74,   74,  179,  180,
       74,  183,  188,  182,  184,  191,   74,   74,   74,  189,
      181,   74,  185,  192,  186,  190,  193,  201,  187,   74,

      194,  195,  166,  167,  199,   74,  196,  196,   74,  188,
       74,  191,  168,  168,  200,  189,   74,  204,   74,   74,
      202,  212,  203,  193,  201,  205,  194,  195,   74,   74,
      199,   74,  206,  207,  210,   74,  208,  197,  209,   74,
      200,   74,   74,  211,  204,   74,  202,  212,  203,   74,
      213,   74,  205,   74,   74,  215,   74,  214,  206,  217,
      207,  210,  208,  216,  209,  196,  196,   74,  218,  211,
       74,  219,   74,  220,  222,   74,   74,  213,  223,   74,
      228,   74,  215,  224,  214,  217,   74,   74,  221,  216,
      229,   74,   74,   74,   74,  218,  226,   74,  219,  225,

      220,  222,  227,   74,   74,  223,  228,  231,   74,  235,
      224,  233,  230,   74,  221,   74,  232,  229,  234,   74,
       74,   74,   74,  226,  236,  225,   74,   74,  227,   74,
       74,   74,   74,  231,   74,  128,  235,  233,  230,  197,
       74,   74,  232,   74,  234,   74,   74,   74,   74,  128,
      128,  236,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   58,   58,   58,   58,   58,   58,   58,   58,
       71,   71,   71,   71,   71,  105,  105,  106,  169,  106,
      106,  106,  106,  106,  106,  106,  107,  107,  107,  107,

      107,  107,  107,  107,  107,  107,  130,  130,  130,  130,
      170,  170,  170,  171,  171,  171,  171,  198,  198,  164,
      163,  162,  161,  160,  159,   74,   74,   74,   74,   74,
       74,   74,  116,   74,   70,   67,   59,  237,    7,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,

      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237
    } ;

static const flex_int16_t yy_chk[713] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    5,    6,   21,    5,    6,
        9,   19,    9,   19,   19,   22,   28,   22,   22,   28,
       21,   25,   25,   57,   29,   57,   37,   30,   22,   65,

       28,   65,   42,   29,   30,   63,   63,   21,   31,   37,
       30,   42,   28,   31,  236,   28,   29,   21,  235,    5,
        6,   29,   37,   30,   30,   22,   31,   33,   42,   29,
       32,   30,   32,   21,   35,   31,   30,   36,   94,   31,
       33,   35,   44,    3,    4,   33,   32,   38,   41,  123,
      123,  232,   40,   33,   33,   35,   32,   94,   32,   36,
       38,   35,   39,   40,   36,   94,   33,   35,   44,   44,
       41,   33,   39,   38,   39,   41,   43,   45,   40,   75,
      231,   73,   43,   39,   43,   45,   61,   61,   64,   39,
       64,   43,   73,   64,   64,   43,   45,   61,   39,   75,

       39,   62,   62,   43,   45,   72,   75,   73,   43,   76,
       43,   45,   62,   66,   83,   66,   66,   43,   56,   77,
       79,  228,   76,  226,   61,   81,   66,  225,   72,   77,
       78,   81,   72,  224,   79,   76,   56,   83,   82,   62,
       56,   83,   80,  220,   84,   77,   79,   56,   82,   80,
       56,   81,   56,   66,   56,  216,   78,   78,   85,   56,
       84,   86,   88,   56,   82,   89,   90,   56,   80,   85,
       84,   88,   98,   56,   91,   86,   56,   95,   56,   89,
       56,   59,  214,   91,   85,   97,  135,   86,   88,   90,
       95,   89,   96,   90,   98,  101,   97,  100,   59,   98,

       91,  213,   59,   95,  102,  100,  103,  101,  135,   59,
      104,   97,   59,  135,   59,  102,   59,  204,   96,   96,
      132,  101,  202,  100,  103,   59,  125,  125,  104,   59,
      102,  127,  127,  103,  133,   59,  139,  104,   59,  124,
       59,  124,   59,  134,  124,  124,  132,  132,  137,  136,
      139,  140,  133,  142,  145,  200,  144,  146,  137,  134,
      136,  133,  139,  142,  143,  149,  154,  150,  152,  134,
      143,  150,  199,  140,  137,  136,  145,  146,  140,  142,
      144,  145,  151,  144,  146,  153,  152,  149,  154,  151,
      143,  150,  149,  154,  150,  152,  155,  174,  150,  153,

      157,  158,  165,  165,  172,  151,  167,  167,  172,  151,
      158,  153,  168,  168,  173,  151,  157,  180,  155,  174,
      177,  190,  178,  155,  174,  181,  157,  158,  173,  177,
      172,  178,  182,  183,  186,  190,  184,  197,  185,  180,
      173,  182,  193,  187,  180,  184,  177,  190,  178,  185,
      194,  181,  181,  183,  187,  201,  186,  195,  182,  205,
      183,  186,  184,  203,  185,  196,  196,  192,  206,  187,
      205,  207,  194,  208,  210,  191,  203,  194,  211,  195,
      219,  201,  201,  212,  195,  205,  206,  189,  209,  203,
      221,  219,  208,  207,  209,  206,  217,  210,  207,  215,

      208,  210,  218,  212,  211,  211,  219,  223,  221,  233,
      212,  229,  222,  215,  209,  218,  227,  221,  230,  217,
      222,  229,  223,  217,  234,  215,  188,  179,  218,  230,
      227,  233,  176,  223,  175,  171,  233,  229,  222,  169,
      156,  148,  227,  147,  230,  141,  234,  138,  131,  130,
      129,  234,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  240,  240,  240,  240,  240,  240,  240,  240,
      241,  241,  241,  241,  241,  242,  242,  243,  128,  243,
      243,  243,  243,  243,  243,  243,  244,  244,  244,  244,

      244,  244,  244,  244,  244,  244,  245,  245,  245,  245,
      246,  246,  246,  247,  247,  247,  247,  248,  248,  122,
      121,  120,  119,  118,  117,  105,   99,   93,   92,   87,
       74,   71,   58,   34,   27,   23,   12,    7,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,

      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[91] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pasc600.l"
/* Xeimerino Examino 2019 - 2020
Lektikos Analyths pasc600

Dimitris Gennimatas 1459
Thanasis Makrygiannis 1058
Giannis Mpatsios 1048
*/
#line 10 "pasc600.l"
    
    #include <math.h>
    #include <stdlib.h>
    #include <stdio.h>
    #include "pasc600.tab.h" 
    #include <string.h>
    
    int value ;
    int token_num = 1 ; // holds value of sequence number of token 
    int error_num=0; 
    char * str ;
    char buf[100];
    char *s ;
    int extline =0; // boolean to see if string extends in another line 
    

#line 736 "lex.yy.c"
#define YY_NO_INPUT 1
/* Don't seperate lower-case from upper-case */
/* Declaration for comments automaton */

/* Declaration of sconst automaton */

/* Define */
/*----------Identifiers ID---------------------*/
/*----------Unsigned whole numbers ICONST---------------------*/
/*----------Unsigned real numbers RCONST---------------------*/
/* CCONST   '[ !"#$%&'()*+,-./0123456789:;=<>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{|}~]' */ 
/* Only 1 ascii character between''. exception special characters */ 
#line 749 "lex.yy.c"

#define INITIAL 0
#define comment 1
#define sconst 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 77 "pasc600.l"

#line 968 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 238 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 639 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 78 "pasc600.l"
{
    printf("%d. TOKEN FOUND = PROGRAM, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_PROGRAM;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 85 "pasc600.l"
{
    printf("%d. TOKEN FOUND = CONST, LINE = %d\n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_CONST;
} 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 91 "pasc600.l"
{
    printf("%d. TOKEN FOUND = TYPE, LINE = %d\n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_TYPE;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 97 "pasc600.l"
{
     printf("%d. TOKEN FOUND = ARRAY, LINE = %d\n",token_num++,yylineno);
     yylval.stringvalue = strdup(yytext);
    return T_ARRAY;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 103 "pasc600.l"
{
    printf("%d. TOKEN FOUND = OF, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_OF;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 109 "pasc600.l"
{
    printf("%d. TOKEN FOUND = VAR, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_VAR;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 115 "pasc600.l"
{
    printf("%d. TOKEN FOUND = FORWARD, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_FORWARD;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 121 "pasc600.l"
{
    printf("%d. TOKEN FOUND = FUNCTION, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_FUNCTION;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 127 "pasc600.l"
{
    printf("%d. TOKEN FOUND = PROCEDURE, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_PROCEDURE;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 133 "pasc600.l"
{
    printf("%d. TOKEN FOUND = INTEGER, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_INTEGER;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 139 "pasc600.l"
{
    printf("%d. TOKEN FOUND = REAL, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_REAL;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 145 "pasc600.l"
{
    printf("%d. TOKEN FOUND = BOOLEAN, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_BOOLEAN;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 151 "pasc600.l"
{
    printf("%d. TOKEN FOUND = CHAR, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_CHAR;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 157 "pasc600.l"
{
    printf("%d. TOKEN FOUND = STRING, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_STRING;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 163 "pasc600.l"
{
    printf("%d. TOKEN FOUND = BEGIN, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_BEGIN;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 169 "pasc600.l"
{
   printf("%d. TOKEN FOUND = END, LINE = %d \n",token_num++,yylineno);
   yylval.stringvalue = strdup(yytext);
   return T_END;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 175 "pasc600.l"
{
    printf("%d. TOKEN FOUND = IF, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_IF;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 181 "pasc600.l"
{
    printf("%d. TOKEN FOUND = THEN, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_THEN;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 187 "pasc600.l"
{
    printf("%d. TOKEN FOUND = ELSE, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_ELSE;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 193 "pasc600.l"
{
   printf("%d. TOKEN FOUND = CASE, LINE = %d \n",token_num++,yylineno);
   yylval.stringvalue = strdup(yytext);
   return T_CASE;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 199 "pasc600.l"
{
    printf("%d. TOKEN FOUND = OTHERWISE, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_OTHERWISE;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 205 "pasc600.l"
{
    printf("%d. TOKEN FOUND = WHILE, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_WHILE;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 211 "pasc600.l"
{
    printf("%d. TOKEN FOUND = DO, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_DO;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 217 "pasc600.l"
{
    printf("%d. TOKEN FOUND = FOR, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_FOR;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 223 "pasc600.l"
{
    printf("%d. TOKEN FOUND = DOWNTO, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_DOWNTO;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 229 "pasc600.l"
{
    printf("%d. TOKEN FOUND = TO, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_TO;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 235 "pasc600.l"
{
    printf("%d. TOKEN FOUND = READ, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_READ;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 241 "pasc600.l"
{
    printf("%d. TOKEN FOUND = WRITE, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_WRITE;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 247 "pasc600.l"
{
    printf("%d. TOKEN FOUND = LENGTH, LINE = %d \n",token_num++,yylineno);
    yylval.stringvalue = strdup(yytext);
    return T_LENGTH;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 254 "pasc600.l"
{
  printf("%d. TOKEN FOUND = BCONST: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_BCONST;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 260 "pasc600.l"
{
  printf("%d. TOKEN FOUND = BCONST: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_BCONST;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 267 "pasc600.l"
{
  printf("%d. TOKEN FOUND = RELOP: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_RELOP;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 273 "pasc600.l"
{
  printf("%d. TOKEN FOUND = RELOP: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_RELOP;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 279 "pasc600.l"
{
  printf("%d. TOKEN FOUND = RELOP: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_RELOP;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 285 "pasc600.l"
{
  printf("%d. TOKEN FOUND = RELOP: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_RELOP;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 291 "pasc600.l"
{
  printf("%d. TOKEN FOUND = RELOP: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_RELOP;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 297 "pasc600.l"
{
  printf("%d. TOKEN FOUND = ADDOP: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_ADDOP;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 303 "pasc600.l"
{
  printf("%d. TOKEN FOUND = ADDOP: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_ADDOP;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 309 "pasc600.l"
{
  printf("%d. TOKEN FOUND = OR: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_OROP;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 315 "pasc600.l"
{
  printf("%d. TOKEN FOUND = MULDIVANDOP: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_MULDIVANDOP;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 321 "pasc600.l"
{
  printf("%d. TOKEN FOUND = MULDIVANDOP: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_MULDIVANDOP;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 327 "pasc600.l"
{
  printf("%d. TOKEN FOUND = MULDIVANDOP: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_MULDIVANDOP;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 333 "pasc600.l"
{
  printf("%d. TOKEN FOUND = MULDIVANDOP: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_MULDIVANDOP;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 339 "pasc600.l"
{
  printf("%d. TOKEN FOUND = MULDIVANDOP: %s, LINE = %d \n",token_num++,yytext,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_MULDIVANDOP;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 345 "pasc600.l"
{
  printf("%d. TOKEN FOUND = NOTOP, LINE = %d \n",token_num++,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_NOTOP;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 351 "pasc600.l"
{
  printf("%d. TOKEN FOUND = LPAREN, LINE = %d \n",token_num++,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_LPAREN;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 357 "pasc600.l"
{
  printf("%d. TOKEN FOUND = RPAREN, LINE = %d \n",token_num++,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_RPAREN;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 363 "pasc600.l"
{
  printf("%d. TOKEN FOUND = SEMI, LINE = %d \n",token_num++,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_SEMI;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 369 "pasc600.l"
{
 printf("%d. TOKEN FOUND = DOT, LINE = %d \n",token_num++,yylineno);
 yylval.stringvalue = strdup(yytext);
  return T_DOT;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 375 "pasc600.l"
{
  printf("%d. TOKEN FOUND = COMMA, LINE = %d \n",token_num++,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_COMMA;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 382 "pasc600.l"
{
  printf("%d. TOKEN FOUND = EQU, LINE = %d \n",token_num++,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_EQU;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 388 "pasc600.l"
{
  printf("%d. TOKEN FOUND = COLON, LINE = %d \n",token_num++,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_COLON;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 394 "pasc600.l"
{
  printf("%d. TOKEN FOUND = LBRACK, LINE = %d \n",token_num++,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_LBRACK;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 400 "pasc600.l"
{
  printf("%d. TOKEN FOUND = RBRACK, LINE = %d \n",token_num++,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_RBRACK;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 406 "pasc600.l"
{
  printf("%d. TOKEN FOUND = ASSIGN, LINE = %d \n",token_num++,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_ASSIGN;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 412 "pasc600.l"
{
  printf("%d. TOKEN FOUND = DOTDOT, LINE = %d \n",token_num++,yylineno);
  yylval.stringvalue = strdup(yytext);
  return T_DOTDOT;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 418 "pasc600.l"
{ 
printf("%d. TOKEN FOUND = ID:%s, LINE = %d \n",token_num++,yytext,yylineno);
yylval.stringvalue = strdup(yytext);
return T_ID;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 424 "pasc600.l"
{
value = atoi(yytext);
yylval.intvalue = value;
printf("%d. TOKEN FOUND = ICONST:%d, LINE = %d \n",token_num++,value,yylineno);
return T_ICONST;
    }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 431 "pasc600.l"
{ 
str = yytext;
value = strtoul(str+2,NULL,16); // str+2 ignore 0x and store int to value. this value is going to be assigned to yylval
printf("%d. TOKEN FOUND = ICONSTHEX: DEC_VAL= %d, HEX_VAL= %s, LINE = %d \n",token_num++,value,yytext,yylineno); 
yylval.intvalue = value;
return T_ICONST;
    }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 439 "pasc600.l"
{
char *s = yytext; 
s++;
printf("%d. TOKEN FOUND = CCONST: %c, LINE = %d \n",token_num++,*s,yylineno);
yylval.stringvalue = strdup(yytext);
return T_CCONST;
    }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 447 "pasc600.l"
{
char *s = yytext; 
s++;
printf("%d. TOKEN FOUND = CCONSTLF: %c%c, LINE = %d \n",token_num++,*s,*(s+1),yylineno); 
yylval.stringvalue = strdup(yytext);
return T_CCONST;
    } 
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 456 "pasc600.l"
{
char *s = yytext; 
s++;
printf("%d. TOKEN FOUND = CCONSTFF: %c%c, LINE = %d \n",token_num++,*s,*(s+1),yylineno); 
yylval.stringvalue = strdup(yytext);
return T_CCONST;
    }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 465 "pasc600.l"
{
char *s = yytext;
s++;
printf("%d. TOKEN FOUND = CCONSTHT: %c%c, LINE = %d \n",token_num++,*s,*(s+1),yylineno); 
yylval.stringvalue = strdup(yytext);
return T_CCONST;
    }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 473 "pasc600.l"
{
char *s = yytext; 
s++;    
printf("%d. TOKEN FOUND = CCONSTHR: %c%c, LINE = %d \n",token_num++,*s,*(s+1),yylineno);
yylval.stringvalue = strdup(yytext);
return T_CCONST;
    }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 481 "pasc600.l"
{
char *s = yytext;
s++;    
printf("%d. TOKEN FOUND = CCONSTBS: %c%c, LINE = %d \n",token_num++,*s,*(s+1),yylineno);
yylval.stringvalue = strdup(yytext);
return T_CCONST;
    }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 489 "pasc600.l"
{
char *s = yytext; 
s++;    
printf("%d. TOKEN FOUND = CCONSTVT: %c%c, LINE = %d \n",token_num++,*s,*(s+1),yylineno);
yylval.stringvalue = strdup(yytext);
return T_CCONST; 
    }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 497 "pasc600.l"
{
double value = atof(yytext); 
printf("%d. TOKEN FOUND = RCONST1: %s, LINE = %d \n",token_num++,yytext,yylineno); 
yylval.doublevalue = value;
return T_RCONST;
    }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 504 "pasc600.l"
{
double value = atof(yytext); 
printf("%d. TOKEN FOUND = RCONST2: %s, LINE = %d \n",token_num++,yytext,yylineno); 
yylval.doublevalue = value;
return T_RCONST;
    }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 511 "pasc600.l"
{
char * end;
double value = strtod(yytext,&end); // convert hex to double 
printf("%d. TOKEN FOUND = RCONSTHEX: DEC_VAL = %lf HEX_VAL = %s, LINE = %d \n",token_num++,value,yytext,yylineno);
yylval.doublevalue = value;
return T_RCONST;
    }
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 519 "pasc600.l"
{ }  //ignore newline 
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 520 "pasc600.l"
{ } //ignore whitespace / tab 
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 522 "pasc600.l"
{return T_EOF;}
	YY_BREAK
/*Start of COMMENTS*/
case 72:
YY_RULE_SETUP
#line 526 "pasc600.l"
{BEGIN(comment);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 528 "pasc600.l"
; // ignore all characters except } 
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 529 "pasc600.l"

	YY_BREAK
case YY_STATE_EOF(comment):
#line 530 "pasc600.l"
{printf("Unexpected File End (Unterminated Comment).\n");exit(1);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 531 "pasc600.l"
{BEGIN(INITIAL);}
	YY_BREAK
/*End of  COMMENTS */
/*start of SCONST*/
case 76:
YY_RULE_SETUP
#line 536 "pasc600.l"
{ BEGIN(sconst); s=buf; } //Start State sconst
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 538 "pasc600.l"
{
    *s = 0; //reset the sconst 
    BEGIN(INITIAL); // Exit sconst 
    if (extline == 1){
    printf("%d. TOKEN FOUND = SCONST: %s, EXTENDS IN LINES = %d--%d \n",token_num++,buf,yylineno-1,yylineno); 
    extline = 0; //print sconst if it extends in another line 
    return T_SCONST;
        }
    else{
    printf("%d. TOKEN FOUND = SCONST: %s, LINE = %d \n",token_num++,buf,yylineno);// print the sconst
    return T_SCONST;
    } 
    }
	YY_BREAK
/*special cases */
case 78:
YY_RULE_SETUP
#line 553 "pasc600.l"
{ *s++ = '\n';}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 554 "pasc600.l"
{ *s++ = '\f';}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 555 "pasc600.l"
{ *s++ = '\t';} 
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 556 "pasc600.l"
{ *s++ = '\r';}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 557 "pasc600.l"
{ *s++ = '\b';}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 558 "pasc600.l"
{ *s++ = '\v';}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 559 "pasc600.l"
{*s++ = '\"';}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 560 "pasc600.l"
{*s++ = '\\';}
	YY_BREAK
case YY_STATE_EOF(sconst):
#line 561 "pasc600.l"
{printf("Unexpected File End(Unterminated SCONST).\n");}
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 563 "pasc600.l"
{*s++ = yytext[1]; extline=1;} // allows the sconst to continue on the next line 
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 567 "pasc600.l"
{printf("ERROR: Invalid SCONST\n");}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 569 "pasc600.l"
{ *s++ = *yytext; } // for all the other cases save yytext to str_buf
	YY_BREAK
/* end of SCONST */
/* All other cases not matching any of the above */
case 89:
YY_RULE_SETUP
#line 574 "pasc600.l"
{
    error_num++ ;
    printf("ERROR %d: INVALID TOKEN --> %s, AT LINE %d\n",error_num,yytext,yylineno);
    }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 581 "pasc600.l"
ECHO;
	YY_BREAK
#line 1819 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 238 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 238 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 237);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 581 "pasc600.l"





/*
int main(int argc, char* argv[]){
    
    //int token;
    
    yyin = fopen(argv[1], "r"); //read only 
    //token=yylex();  //get first token 
    
    while(yylex() != T_EOF){ //until the file ends continue reading tokens 
    yylex();
    }
    
    fclose(yyin);// close file when we are done 
    printf("-----Lexical Analysis Completed-----\n");
    printf("-----Tokens Found: %d--------------\n", token_num-1 );
    exit(1);
    }
*/
    




